{
    "openapi" : "3.0.3",
    "info" : {
        "title" : "TodoList RESTful API",
        "description" : "OpenAPI for TodoList RESTful API",
        "version" : "1",
        "contact" : {
            "name" : "Vidky Adhi Pradana",
            "email" : "vidky@gmail.com",
            "url" : "https://www.programmerzamannow.com"
        }, 
        "license" : {
            "name" : "APACHE 2.0",
            "url" : "https://www.apache.org/licenses/LICENSE-2.0"
        }
    },
    "servers" : [
        {
            "url" : "https://{environment}.programmerzamannow.com/api/v1",
            "variables":{
                "environment": {
                    "description" : "Server Environment",
                    "default" : "dev",
                    "enum" : [
                        "dev",
                        "qa",
                        "prod"
                    ]
                }
            }
        }
    ],
    "externalDocs" : {
        "description" : "Youtube Vidky Adhi",
        "url" : "https://www.youtube.com/"
    },
    "paths": {
        "/todolist" : {
            "get" : {
                "tags" : ["Todolist"],

                "summary" : "Get all todolist",
                "description" : "Get all active todolist by default",
                "parameters" : [
                    {
                        "name" : "include_done",
                        "in" : "query",
                        "required" : false,
                        "description" : "Is include done todolist",
                        "schema" : {
                            "type" : "boolean",
                            "nullable" : true,
                            "default" : false
                        }
                    },
                    {
                        "name" : "name",
                        "in" : "query",
                        "required" : false,
                        "description" : "Filter todolist by name",
                        "schema" : {
                            "type" : "string",
                            "nullable": true,
                            "minLength" : 1,
                            "maxLength" : 100
                    },
                        "examples" : {
                            "java" : {
                                "description" : "example name java",
                                "value" : "Java"
                            },
                            "php" : {
                                "description" : "example name PHP",
                                "value" : "PHP"
                            }
                        }
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "Success get all todolist",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "$ref" :"#/components/schemas/ArrayTodolist"
                                },
                                "examples" : {
                                    "success" : {
                                        "description" : "Example success get all todolist",
                                        "value" : [
                                            {
                                                "id" : "1",
                                                "name" : "Java",
                                                "priority" : 3,
                                                "tags" : [
                                                    "Java", "Programming"
                                                ]
                                            },
                                            {
                                                "id" : "2",
                                                "name" : "PHP",
                                                "priority" : 5,
                                                "tags" : [
                                                    "PHP", "Programming"
                                                ]
                                            }

                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }, 
            "post" : {
                "tags" : ["Todolist"],
                "summary" : "Create new todolist",
                "description": "Create new todolist to database",
                "requestBody" : {
                    "required" : true,
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" :"#/components/schemas/CreateOrUpdateTodolist"
                            },
                                "examples" : {
                                "java" : {
                                    "description" : "Example create todolist Java",
                                    "value" : {
                                        "name" : "Java",
                                        "priority" : 3,
                                        "tags" : [
                                            "Java",
                                            "Programming"
                                        ]
                                    }
                                },
                                "php" : {
                                    "description" : "Example create todoList PHP",
                                    "value" : {
                                        "name" : "PHP",
                                        "priority" : 1,
                                        "tags" : ["PHP", "Cuan"]
                                    }
                                 }
                            }
                        }
                    }
                },
                "responses" : {
                    "200" : {
                        "description" : "success create todolist",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "$ref" :"#/components/schemas/Todolist"
                                },
                                "examples" : {
                                    "java" : {
                                        "description" : "success create java todolist",
                                        "value" : {
                                            "id" : "1",
                                            "name" : "Java",
                                            "priority" : 3,
                                            "tags" : [
                                                "Java",
                                                "Programming"
                                            ]
                                        }
                                    },
                                    "php" : {
                                        "description" : "success create php todolist",
                                        "value" : {
                                            "id" : "2",
                                            "name" : "PHP",
                                            "priority" : 5,
                                            "tags" : [
                                                "PHP",
                                                "Programming"]  
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/todolist/{todolistId}" : {
            "put" : {
                "tags" : ["Todolist"],
                "summary" : "Update existing todolist",
                "description" : "Update existing todolist in database",
                "parameters" : [
                    {
                        "$ref" :"#/components/parameters/TodolistId"
                    }
                ],
                "requestBody" : {
                    "required" : true,
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" :"#/components/schemas/CreateOrUpdateTodolist"
                            },
                            "examples" : {
                                "java" : {
                                    "description" : "Example create todolist Java",
                                    "value" : {
                                        "name" : "Java",
                                        "priority" : 3,
                                        "tags" :[
                                            "Java" , "Programming"
                                        ]
                                    }
                                }, 
                                "php" : {
                                    "description" : "Example create todolist PHP",
                                    "value" : {
                                        "name" : "PHP",
                                        "priority" : 3,
                                        "tags" :[
                                            "PHP" , "Programming"
                                        ]
                                    }
                                }
                               

                            }
                        }
                    }
                },
                "responses" : {
                    "200" : {
                        "description" : "success update todolist",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "$ref" : "#/components/schemas/Todolist"
                                },
                                "examples" : {
                                    "java" : {
                                        "description" : "success update java todolist",
                                        "value" : {
                                            "id" : "1",
                                            "name" : "Java",
                                            "priority" : 3,
                                            "tags" : [
                                                "Java",
                                                "Programming"
                                            ]
                                        }
                                    },
                                    "php" : {
                                        "description" : "success update php todolist",
                                        "value" : {
                                            "id" : "2",
                                            "name" : "PHP",
                                            "priority" : 5,
                                            "tags" : [
                                                "PHP",
                                                "Programming"]  
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete" : {
                "tags" : ["Todolist"],
                "summary" :"Delete existing todolist",
                "description" : "Delete existing todolist in database",
                "parameters" : [
                    {
                        "$ref" : "#/components/parameters/TodolistId"
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "success delete todolist",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "properties" : {
                                        "success" : {
                                            "type" : "boolean"
                                        }
                                    }
                                },
                                "examples" : {
                                    "success" : {
                                        "description" : "success delete todolist",
                                        "value" : {
                                            "success" : true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404" : {
                        "description" : "failed delete todolist",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",
                                    "properties" : {
                                        "success" : {
                                            "type" : "boolean"
                                        }
                                    }
                                },
                                "examples" : {
                                    "failed" : {
                                        "description" : "Failed delete todolist",
                                        "value" : {
                                            "success" : false
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components" : {
        "parameters" : {
            "TodolistId" :  {
                "name" :"todolistId",
                "in": "path",
                "required" : true,
                "description" : "Todolist for updated/delete",
                "schema" : {
                    "type" : "string",
                    "minLength" : 1,
                    "maxLength": 100
                 },
                 "examples" : {
                     "java" : {
                         "description" : "sample todoList id for java",
                         "value" : "1"
                     },
                     "php" : {
                         "description" : "simple todoList id for PHP",
                         "value" : "2"
                     }
                 }
            }
        },
        "schemas" : {
            "Todolist" : {
                "type" : "object",
                "properties" : {
                    "id" : {
                        "type" : "string"
                    }, 
                    "name" : {
                        "type" : "string"
                    }, 
                    "priority" : {
                        "type" : "number"
                    }, 
                    "tags" : {
                        "type" : "array",
                        "items" : {
                            "type" : "string"
                        }
                    }
                 }
            }, 
            "CreateOrUpdateTodolist" : {
                "type" : "object",
                "properties" : {
                    "name" : {
                        "type" : "string",
                        "minLength" : 1,
                        "required" : true
                    },
                    "priority" : {
                        "type" : "integer",
                        "format" : "int32",
                        "required" : true,
                        "default" : 1
                    },
                    "tags" : {
                        "type" : "array",
                        "required" : false,
                        "minItems" : 1,
                        "items" : {
                            "type" : "string",
                            "minLength" : 1
                        }
                    }
                }
            },
            "ArrayTodolist" : {
                "type" : "array",
                "items" :{
                    "$ref" :"#/components/schemas/Todolist"
                }
            }

        }
    }
}